# docker-compose up -d
version: '3.8'
services:
    rabbitmq:
        image: 'rabbitmq:3-management'
        container_name: 'rabbit-server'
        ports:
            - '8080:15672' # port to rabbitmq dashboard
            - '5672:5672'
        environment:
            hostname: rmq
    sqlserver:
        image: 'mcr.microsoft.com/mssql/server:2019-latest'
        container_name: sqlserver-container
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: YourStrong@Passw0rd
        ports:
            - '1433:1433'
